using System;
using System.Collections.Generic;

namespace DataAPI.Models
{
    public partial class F4211
    {
        public string Sdkcoo { get; set; }
        public decimal? Sddoco { get; set; }
        public string Sddcto { get; set; }
        public decimal? Sdlnid { get; set; }
        public string Sdsfxo { get; set; }
        public string Sdmcu { get; set; }
        public string Sdco { get; set; }
        public string Sdokco { get; set; }
        public string Sdoorn { get; set; }
        public string Sdocto { get; set; }
        public decimal? Sdogno { get; set; }
        public string Sdrkco { get; set; }
        public string Sdrorn { get; set; }
        public string Sdrcto { get; set; }
        public decimal? Sdrlln { get; set; }
        public string Sddmct { get; set; }
        public decimal? Sddmcs { get; set; }
        public decimal? Sdan8 { get; set; }
        public decimal? Sdshan { get; set; }
        public decimal? Sdpa8 { get; set; }
        public decimal? Sddrqj { get; set; }
        public DateTime? SddrqjGr { get; set; }
        public decimal? Sdtrdj { get; set; }
        public DateTime? SdtrdjGr { get; set; }
        public decimal? Sdpddj { get; set; }
        public DateTime? SdpddjGr { get; set; }
        public decimal? Sdaddj { get; set; }
        public DateTime? SdaddjGr { get; set; }
        public decimal? Sdivd { get; set; }
        public DateTime? SdivdGr { get; set; }
        public decimal? Sdcndj { get; set; }
        public DateTime? SdcndjGr { get; set; }
        public decimal? Sddgl { get; set; }
        public decimal? Sdrsdj { get; set; }
        public DateTime? SdrsdjGr { get; set; }
        public decimal? Sdpefj { get; set; }
        public DateTime? SdpefjGr { get; set; }
        public decimal? Sdppdj { get; set; }
        public DateTime? SdppdjGr { get; set; }
        public string Sdvr01 { get; set; }
        public string Sdvr02 { get; set; }
        public decimal? Sditm { get; set; }
        public string Sdlitm { get; set; }
        public string Model { get; set; }
        public string Sdaitm { get; set; }
        public string Sdlocn { get; set; }
        public string Sdlotn { get; set; }
        public string Sdfrgd { get; set; }
        public string Sdthgd { get; set; }
        public decimal? Sdfrmp { get; set; }
        public decimal? Sdthrp { get; set; }
        public decimal? Sdexdp { get; set; }
        public string Sddsc1 { get; set; }
        public string Sddsc2 { get; set; }
        public string Sdlnty { get; set; }
        public string Sdnxtr { get; set; }
        public string SdnxtrTxt { get; set; }
        public string Sdlttr { get; set; }
        public string SdlttrTxt { get; set; }
        public string Sdemcu { get; set; }
        public string Sdrlit { get; set; }
        public decimal? Sdktln { get; set; }
        public decimal? Sdcpnt { get; set; }
        public decimal? Sdrkit { get; set; }
        public decimal? Sdktp { get; set; }
        public string Sdsrp1 { get; set; }
        public string Sdsrp2 { get; set; }
        public string Sdsrp3 { get; set; }
        public string Sdsrp4 { get; set; }
        public string Sdsrp5 { get; set; }
        public string Sdprp1 { get; set; }
        public string Sdprp2 { get; set; }
        public string Sdprp3 { get; set; }
        public string Sdprp4 { get; set; }
        public string Sdprp5 { get; set; }
        public string Sduom { get; set; }
        public decimal? Sduorg { get; set; }
        public decimal? Sdsoqs { get; set; }
        public decimal? Sdsobk { get; set; }
        public decimal? Sdsocn { get; set; }
        public decimal? Sdsone { get; set; }
        public decimal? Sduopn { get; set; }
        public decimal? Sdqtyt { get; set; }
        public decimal? Sdqrlv { get; set; }
        public string Sdcomm { get; set; }
        public string Sdotqy { get; set; }
        public decimal? Sduprc { get; set; }
        public decimal? Sdaexp { get; set; }
        public decimal? Sdaopn { get; set; }
        public string Sdprov { get; set; }
        public string Sdtpc { get; set; }
        public string Sdapum { get; set; }
        public decimal? Sdlprc { get; set; }
        public decimal? Sduncs { get; set; }
        public decimal? Sdecst { get; set; }
        public string Sdcsto { get; set; }
        public decimal? Sdtcst { get; set; }
        public string Sdinmg { get; set; }
        public string Sdptc { get; set; }
        public string Sdryin { get; set; }
        public string Sddtbs { get; set; }
        public decimal? Sdtrdc { get; set; }
        public decimal? Sdfun2 { get; set; }
        public string Sdasn { get; set; }
        public string Sdprgr { get; set; }
        public string Sdclvl { get; set; }
        public decimal? Sdcadc { get; set; }
        public string Sdkco { get; set; }
        public decimal? Sddoc { get; set; }
        public string Sddct { get; set; }
        public decimal? Sdodoc { get; set; }
        public string Sdodct { get; set; }
        public string Sdokc { get; set; }
        public decimal? Sdpsn { get; set; }
        public decimal? Sddeln { get; set; }
        public string Sdtax1 { get; set; }
        public string Sdtxa1 { get; set; }
        public string Sdexr1 { get; set; }
        public string Sdatxt { get; set; }
        public string Sdprio { get; set; }
        public string Sdresl { get; set; }
        public string Sdback { get; set; }
        public string Sdsbal { get; set; }
        public string Sdapts { get; set; }
        public string Sdlob { get; set; }
        public string Sdeuse { get; set; }
        public string Sddtys { get; set; }
        public string Sdntr { get; set; }
        public decimal? Sdvend { get; set; }
        public decimal? Sdcars { get; set; }
        public string Sdmot { get; set; }
        public string Sdrout { get; set; }
        public string Sdstop { get; set; }
        public string Sdzon { get; set; }
        public string Sdcnid { get; set; }
        public string Sdfrth { get; set; }
        public string Sdshcm { get; set; }
        public string Sdshcn { get; set; }
        public string Sdsern { get; set; }
        public string Sduom1 { get; set; }
        public decimal? Sdpqor { get; set; }
        public string Sduom2 { get; set; }
        public decimal? Sdsqor { get; set; }
        public string Sduom4 { get; set; }
        public decimal? Sditwt { get; set; }
        public string Sdwtum { get; set; }
        public decimal? Sditvl { get; set; }
        public string Sdvlum { get; set; }
        public string Sdrprc { get; set; }
        public string Sdorpr { get; set; }
        public string Sdorp { get; set; }
        public string Sdcmgp { get; set; }
        public string Sdglc { get; set; }
        public decimal? Sdctry { get; set; }
        public decimal? Sdfy { get; set; }
        public string Sdso01 { get; set; }
        public string Sdso02 { get; set; }
        public string Sdso03 { get; set; }
        public string Sdso04 { get; set; }
        public string Sdso05 { get; set; }
        public string Sdso06 { get; set; }
        public string Sdso07 { get; set; }
        public string Sdso08 { get; set; }
        public string Sdso09 { get; set; }
        public string Sdso10 { get; set; }
        public string Sdso11 { get; set; }
        public string Sdso12 { get; set; }
        public string Sdso13 { get; set; }
        public string Sdso14 { get; set; }
        public string Sdso15 { get; set; }
        public string Sdacom { get; set; }
        public string Sdcmcg { get; set; }
        public string Sdrcd { get; set; }
        public decimal? Sdgrwt { get; set; }
        public string Sdgwum { get; set; }
        public string Sdsbl { get; set; }
        public string Sdsblt { get; set; }
        public string Sdlcod { get; set; }
        public string Sdupc1 { get; set; }
        public string Sdupc2 { get; set; }
        public string Sdupc3 { get; set; }
        public string Sdswms { get; set; }
        public string Sduncd { get; set; }
        public string Sdcrmd { get; set; }
        public string Sdcrcd { get; set; }
        public decimal? Sdcrr { get; set; }
        public decimal? Sdfprc { get; set; }
        public decimal? Sdfup { get; set; }
        public decimal? Sdfea { get; set; }
        public decimal? Sdfuc { get; set; }
        public decimal? Sdfec { get; set; }
        public string Sdurcd { get; set; }
        public decimal? Sdurdt { get; set; }
        public DateTime? SdurdtGr { get; set; }
        public decimal? Sdurat { get; set; }
        public decimal? Sdurab { get; set; }
        public string Sdurrf { get; set; }
        public string Sdtorg { get; set; }
        public string Sduser { get; set; }
        public string Sdpid { get; set; }
        public string Sdjobn { get; set; }
        public decimal? Sdupmj { get; set; }
        public DateTime? SdupmjGr { get; set; }
        public decimal? Sdtday { get; set; }
        public string Sdso16 { get; set; }
        public string Sdso17 { get; set; }
        public string Sdso18 { get; set; }
        public string Sdso19 { get; set; }
        public string Sdso20 { get; set; }
        public string Sdir01 { get; set; }
        public string Sdir02 { get; set; }
        public string Sdir03 { get; set; }
        public string Sdir04 { get; set; }
        public string Sdir05 { get; set; }
        public decimal? Sdsoor { get; set; }
        public string Sdvr03 { get; set; }
        public decimal? Sddeid { get; set; }
        public string Sdpsig { get; set; }
        public string Sdrlnu { get; set; }
        public decimal? Sdpmdt { get; set; }
        public decimal? Sdrltm { get; set; }
        public decimal? Sdrldj { get; set; }
        public decimal? Sddrqt { get; set; }
        public decimal? Sdadtm { get; set; }
        public decimal? Sdoptt { get; set; }
        public decimal? Sdpdtt { get; set; }
        public decimal? Sdpstm { get; set; }
        public string Sdxdck { get; set; }
        public decimal? Sdxpty { get; set; }
        public string Sddual { get; set; }
        public string Sdbsc { get; set; }
        public string Sdcbsc { get; set; }
        public decimal? Sdcord { get; set; }
        public decimal? Sddvan { get; set; }
        public string Sdpend { get; set; }
        public string Sdrfrv { get; set; }
        public decimal? Sdmcln { get; set; }
        public decimal? Sdshpn { get; set; }
        public decimal? Sdrsdt { get; set; }
        public decimal? Sdprjm { get; set; }
        public decimal? Sdoseq { get; set; }
        public string Sdmerl { get; set; }
        public string Sdhold { get; set; }
        public string Sdhdbu { get; set; }
        public string Sddmbu { get; set; }
        public string Sdbcrc { get; set; }
        public decimal? Sdodln { get; set; }
        public decimal? Sdopdj { get; set; }
        public DateTime? SdopdjGr { get; set; }
        public string Sdxkco { get; set; }
        public decimal? Sdxorn { get; set; }
        public string Sdxcto { get; set; }
        public decimal? Sdxlln { get; set; }
        public string Sdxsfx { get; set; }
        public string Sdpoe { get; set; }
        public string Sdpmto { get; set; }
        public decimal? Sdanby { get; set; }
        public string Sdpmtn { get; set; }
        public decimal? Sdnumb { get; set; }
        public decimal? Sdaaid { get; set; }
        public string Sdspattn { get; set; }
        public decimal? Sdpran8 { get; set; }
        public decimal? Sdprcidln { get; set; }
        public decimal? Sdccidln { get; set; }
        public decimal? Sdshccidln { get; set; }
        public decimal? Sdoppid { get; set; }
        public string Sdostp { get; set; }
        public decimal? Sdukid { get; set; }
        public string Sdcatnm { get; set; }
    }
}
